export enum actionTypes {
  ADD_LIST = 'ADD_LIST',
  DELETE_LIST = 'DELETE_LIST',
  MOVE_LIST = 'MOVE_LIST',
  RENAME_LIST = 'RENAME_LIST',

  ADD_TASK = 'ADD_TASK',
  DELETE_TASK = 'DELETE_TASK',
  MOVE_TASK = 'MOVE_TASK',
  RENAME_TASK = 'RENAME_TASK',
  POPOVER_TASK = 'POPOVER_TASK',

  ADD_LABEL_TASK = 'ADD_LABEL_TASK',
  DELETE_LABEL_TASK = 'DELETE_LABEL_TASK',

  EDIT_DESCRIPTION = 'EDIT_DESCRIPTION',
}
